#  Copyright (c) Microsoft Corporation.  All rights reserved.
#  
# THIS SAMPLE CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# WHETHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
# IF THIS CODE AND INFORMATION IS MODIFIED, THE ENTIRE RISK OF USE OR RESULTS IN
# CONNECTION WITH THE USE OF THIS CODE AND INFORMATION REMAINS WITH THE USER. 



set-alias cat        get-content
set-alias cd         set-location
set-alias clear      clear-host
set-alias cp         copy-item
set-alias h          get-history
set-alias history    get-history
set-alias kill       stop-process
set-alias lp         out-printer
set-alias ls         get-childitem
set-alias mount      new-mshdrive
set-alias mv         move-item
set-alias popd       pop-location
set-alias ps         get-process
set-alias pushd      push-location
set-alias pwd        get-location
set-alias r          invoke-history
set-alias rm         remove-item
set-alias rmdir      remove-item
set-alias echo       write-output

set-alias cls        clear-host
set-alias chdir      set-location
set-alias copy       copy-item
set-alias del        remove-item
set-alias dir        get-childitem
set-alias erase      remove-item
set-alias move       move-item
set-alias rd         remove-item
set-alias ren        rename-item
set-alias set        set-variable
set-alias type       get-content

function help
{
    get-help $args[0] | out-host -paging
}

function man
{
    get-help $args[0] | out-host -paging
}

function mkdir
{
    new-item -type directory -path $args
}

function md
{
    new-item -type directory -path $args
}

function prompt
{
    "PS " + $(get-location) + "> "
}

& {
    for ($i = 0; $i -lt 26; $i++) 
    { 
        $funcname = ([System.Char]($i+65)) + ':'
        $str = "function global:$funcname { set-location $funcname } " 
        invoke-expression $str 
    }
}












# SIG # Begin signature block
# MIIXBAYJKoZIhvcNAQcCoIIW9TCCFvECAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUoWtkojNFnh2ZdsrbYLKXNjQn
# b/OgghHRMIIDxDCCAy2gAwIBAgIQR78Zld+NUkZD99ttSA0xpDANBgkqhkiG9w0B
# AQUFADCBizELMAkGA1UEBhMCWkExFTATBgNVBAgTDFdlc3Rlcm4gQ2FwZTEUMBIG
# A1UEBxMLRHVyYmFudmlsbGUxDzANBgNVBAoTBlRoYXd0ZTEdMBsGA1UECxMUVGhh
# d3RlIENlcnRpZmljYXRpb24xHzAdBgNVBAMTFlRoYXd0ZSBUaW1lc3RhbXBpbmcg
# Q0EwHhcNMDMxMjA0MDAwMDAwWhcNMTMxMjAzMjM1OTU5WjBTMQswCQYDVQQGEwJV
# UzEXMBUGA1UEChMOVmVyaVNpZ24sIEluYy4xKzApBgNVBAMTIlZlcmlTaWduIFRp
# bWUgU3RhbXBpbmcgU2VydmljZXMgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
# ggEKAoIBAQCpyrKkzM0grwp9iayHdfC0TvHfwQ+/Z2G9o2Qc2rv5yjOrhDCJWH6M
# 22vdNp4Pv9HsePJ3pn5vPL+Trw26aPRslMq9Ui2rSD31ttVdXxsCn/ovax6k96Oa
# phrIAuF/TFLjDmDsQBx+uQ3eP8e034e9X3pqMS4DmYETqEcgzjFzDVctzXg0M5US
# mRK53mgvqubjwoqMKsOLIYdmvYNYV291vzyqJoddyhAVPJ+E6lTBCm7E/sVK3bkH
# EZcifNs+J9EeeOyfMcnx5iIZ28SzR0OaGl+gHpDkXvXufPF9q2IBj/VNC97QIlao
# lc2uiHau7roN8+RN2aD7aKCuFDuzh8G7AgMBAAGjgdswgdgwNAYIKwYBBQUHAQEE
# KDAmMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC52ZXJpc2lnbi5jb20wEgYDVR0T
# AQH/BAgwBgEB/wIBADBBBgNVHR8EOjA4MDagNKAyhjBodHRwOi8vY3JsLnZlcmlz
# aWduLmNvbS9UaGF3dGVUaW1lc3RhbXBpbmdDQS5jcmwwEwYDVR0lBAwwCgYIKwYB
# BQUHAwgwDgYDVR0PAQH/BAQDAgEGMCQGA1UdEQQdMBukGTAXMRUwEwYDVQQDEwxU
# U0EyMDQ4LTEtNTMwDQYJKoZIhvcNAQEFBQADgYEASmv56ljCRBwxiXmZK5a/gqwB
# 1hxMzbCKWG7fCCmjXsjKkxPnBFIN70cnLwA4sOTJk06a1CJiFfc/NyFPcDGA8Ys4
# h7Po6JcA/s9Vlk4k0qknTnqut2FB8yrO58nZXt27K4U+tZ212eFX/760xX71zwye
# 8Jf+K9M7UhsbOCf3P0owggP/MIIC56ADAgECAhAN6Svw1NgpiBgyBQlemnaIMA0G
# CSqGSIb3DQEBBQUAMFMxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5WZXJpU2lnbiwg
# SW5jLjErMCkGA1UEAxMiVmVyaVNpZ24gVGltZSBTdGFtcGluZyBTZXJ2aWNlcyBD
# QTAeFw0wMzEyMDQwMDAwMDBaFw0wODEyMDMyMzU5NTlaMFcxCzAJBgNVBAYTAlVT
# MRcwFQYDVQQKEw5WZXJpU2lnbiwgSW5jLjEvMC0GA1UEAxMmVmVyaVNpZ24gVGlt
# ZSBTdGFtcGluZyBTZXJ2aWNlcyBTaWduZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IB
# DwAwggEKAoIBAQCyUChI3dNoeoQYRGZ1XX7EuJ9jJv89Q5x8ETgQJVVz2XUnaf1O
# uSBc0wr5oBsq7VVWIWHYHtvkvDNrx+/dozdljhuTDLZTHlx8ZjVfBYpF/nZO31OA
# ooEgna6IXKII9+Uw+e4iN0xCCs7fxh/E1lXpgT+1UqMsqgF68qKqjTX+n+ZdagWf
# PWvjv5bA/sxg+UDnB6BE64FRbqUq8raKECjtj9wGoIZQmntKCA0wHcoQnmv36Viu
# BKlAmbIo6I8WrDzjU29L0zWdtW9kHbOWLLs953nrbXr5FuYmra/vmVO3QCyVuHmq
# /tRSqyl0fkLsOR6iahbmWbskaNgAgEMQh4BrAgMBAAGjgcowgccwNAYIKwYBBQUH
# AQEEKDAmMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC52ZXJpc2lnbi5jb20wDAYD
# VR0TAQH/BAIwADAzBgNVHR8ELDAqMCigJqAkhiJodHRwOi8vY3JsLnZlcmlzaWdu
# LmNvbS90c3MtY2EuY3JsMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMA4GA1UdDwEB
# /wQEAwIGwDAkBgNVHREEHTAbpBkwFzEVMBMGA1UEAxMMVFNBMjA0OC0xLTU0MA0G
# CSqGSIb3DQEBBQUAA4IBAQCHeHDaTlIBIFvgecmCMMT9uRmWvZEAw73Nzcb0Dtj/
# +U3AM2IwEcX1dBvUkt5fnCATsXxFvlDNg+eAF4OnJ5NnE0b7yriYQQPMm1FbBYt/
# qG/zG1AbJC7yaY1sIve7yhaV7Qx0wGh32euZYofBc5D4iXR6I6ujmHuXsfePKXFN
# LnUbSEHa8LUNIFTWd6CXgmNp/QnPivB1uwmb2fkRVSaaYTK+egKwe4a+osOLIix4
# 0TV2vJJzXPm55kwVCiPM5NLUNC5JQBU8D2B6JMalZu+Wz3DrPuf0DX7c0XyjdnFp
# wZxPRzA1IbGirxpiPCvZjqoqB3vYGLNce+KdpW/+PImtMIIEyzCCA7OgAwIBAgIQ
# aguZT8AADKsR2CLvfWx5fjANBgkqhkiG9w0BAQQFADBwMSswKQYDVQQLEyJDb3B5
# cmlnaHQgKGMpIDE5OTcgTWljcm9zb2Z0IENvcnAuMR4wHAYDVQQLExVNaWNyb3Nv
# ZnQgQ29ycG9yYXRpb24xITAfBgNVBAMTGE1pY3Jvc29mdCBSb290IEF1dGhvcml0
# eTAeFw0wMjA1MjMwODAwMDBaFw0xMTA5MjUwODAwMDBaMIGmMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSswKQYDVQQLEyJDb3B5cmlnaHQgKGMp
# IDIwMDAgTWljcm9zb2Z0IENvcnAuMSMwIQYDVQQDExpNaWNyb3NvZnQgQ29kZSBT
# aWduaW5nIFBDQTCCASAwDQYJKoZIhvcNAQEBBQADggENADCCAQgCggEBAMPMII28
# 3/8+UO56wtQkJfZ2ziH/zSpWTsqct4KyNXktAMSoCNVjybel9unBwdaxjJaiB/oP
# toJSmuuCxr0QxajA7muEjlMbu1D6ZAGJwRbUgmgAQHhE9RI4TvtjUeD6PbnlN7Hf
# YwcjO3FANEf0a65G9SdzHiLLQhkeUbZSmtOj0BPGGT9xBm3ylSFEX0LtwMmZZCC4
# wTT8okTme7IdL7im3vSh35shD/5YMUFVOH6vWOfk7Fl5Jav3Ki8RPzh4PkJ/p2jk
# fiJoF+ZKksR4RFJHoU+EiZObwGd76gn7hgN99plxPCunZpjM3y3iKwIaDzRIZfU8
# Eq/xhxwdJlJvzAMCAQOjggEqMIIBJjATBgNVHSUEDDAKBggrBgEFBQcDAzCBogYD
# VR0BBIGaMIGXgBBb0HDvaXKeI1F+FLJNjv/LoXIwcDErMCkGA1UECxMiQ29weXJp
# Z2h0IChjKSAxOTk3IE1pY3Jvc29mdCBDb3JwLjEeMBwGA1UECxMVTWljcm9zb2Z0
# IENvcnBvcmF0aW9uMSEwHwYDVQQDExhNaWNyb3NvZnQgUm9vdCBBdXRob3JpdHmC
# DwDBAIs8PIgR0T72Y+zfQDASBgkrBgEEAYI3FQEEBQIDAwADMB0GA1UdDgQWBBQl
# +CtLXchyVK3l9qAqFxb7wflTgTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAL
# BgNVHQ8EBAMCAUYwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQQFAAOCAQEA
# n2RKdOFpJ1r4BlMnl8ce0YFz0c66gfQa6pOXh6/cjzoCtYsQv9MudHQBO7RAE+5R
# XzzDMptP1ulZyigAlnIV63EvmJjAA+E1QukIL2Ixmfwx89xCrtxPj8w43nBBOGAN
# PCCSKxicB/5Wk6nSS4i9mUoiAoVvROyR5hneK7gVsptw+sXrToMsOnGgMljyNVLb
# kYhA728b5ylCtHDNfWxvGsjbnPrRXor30iyaAF/Z9MKzn3vUO/5TdCpnHYEnonXo
# QJgHGIsYIAtGct/v9+w2be5ryWZTHb01quXLHWpyE0WAHtldh2aKHCymysthAwPe
# CckBsVnAsP3mZpfL+gk7fDCCBTMwggQboAMCAQICCmFGnssABAAAAGUwDQYJKoZI
# hvcNAQEFBQAwgaYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
# DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
# KzApBgNVBAsTIkNvcHlyaWdodCAoYykgMjAwMCBNaWNyb3NvZnQgQ29ycC4xIzAh
# BgNVBAMTGk1pY3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBMB4XDTA2MDQwNDE5NDM0
# NloXDTA3MTAwNDE5NTM0NlowdDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
# bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
# b3JhdGlvbjEeMBwGA1UEAxMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMIIBIjANBgkq
# hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzYGWOK5covLB397Qq5WN1jydH4vDXYYu
# XfCxcvWrrIhqtdqxInsLyMilS5FeIhPp+fUjnbX0bnau7+6kPMfEwFlcP6uzczMm
# pmKBYXmhYvRuiJXQbt3Hn9KkURF2YbpwimWhlhaJp12B0ERm5dtWnkDK/Nx2JC5E
# MADl1n17lRHVWB2j6E8LyYjcotZTmWzKY8qZapqSXkxNEegv01tbXl9So3MtpbuE
# RQ2MGRV2ywjamqZwFehN7Gn9XbJrj+0pUTc4i8ZGSRWUUJiw9Gik194JcWd0nneM
# HYVrl+rnX0XM4OZxDdFjAJN7MZiOC7QTvbPQ7vHfIe6pYGHuN0M9wwIDAQABo4IB
# kjCCAY4wDgYDVR0PAQH/BAQDAgbAMB0GA1UdDgQWBBTu2WupdVPNT+4bThkGHqOc
# q8+U/TATBgNVHSUEDDAKBggrBgEFBQcDAzCBqQYDVR0jBIGhMIGegBQl+CtLXchy
# VK3l9qAqFxb7wflTgaF0pHIwcDErMCkGA1UECxMiQ29weXJpZ2h0IChjKSAxOTk3
# IE1pY3Jvc29mdCBDb3JwLjEeMBwGA1UECxMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
# MSEwHwYDVQQDExhNaWNyb3NvZnQgUm9vdCBBdXRob3JpdHmCEGoLmU/AAB2rEdrE
# AqFmJ7owSwYDVR0fBEQwQjBAoD6gPIY6aHR0cDovL2NybC5taWNyb3NvZnQuY29t
# L3BraS9jcmwvcHJvZHVjdHMvQ29kZVNpZ25QQ0EyLmNybDBPBggrBgEFBQcBAQRD
# MEEwPwYIKwYBBQUHMAKGM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2Vy
# dHMvQ29kZVNpZ25QQ0EyLmNydDANBgkqhkiG9w0BAQUFAAOCAQEAONnvlTibXJgU
# XVRuad8CyOez+9PCTa0vq39UDdoytvhq5g37IRp3PqVoerSVfopc8kPEg5tlfYhQ
# UXyCFPWDc9eivlzKAnDOJmwXvFIUpYnAt+ShzKF1nZFxPRvAVgBWtfiEJtpeM/vW
# JXpemtqm+/TyQRqsVUatSNyROBNYCUnx8zGHH7wEjlsSZQPpC1HQoQyKmb3ZwajQ
# CBUlIbW2V4kc0VuGNaXK/aqH7Kk3P7dDa+Mg8UW8fq7p8VWyoUi8Zb5TNNnJ6AZj
# BAZ4blD/SLub6kNah9utCoD1WcUs5OV/W0rlMnnuIoWSDC2zUFvGwkBYWKvSzeMv
# wc3sbZ83eTGCBJ0wggSZAgEBMIG1MIGmMQswCQYDVQQGEwJVUzETMBEGA1UECBMK
# V2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0
# IENvcnBvcmF0aW9uMSswKQYDVQQLEyJDb3B5cmlnaHQgKGMpIDIwMDAgTWljcm9z
# b2Z0IENvcnAuMSMwIQYDVQQDExpNaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQQIK
# YUaeywAEAAAAZTAJBgUrDgMCGgUAoIG6MBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3
# AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMCMGCSqGSIb3DQEJBDEW
# BBTDAk+4/b2Lma8JCkyLngt3fXPT4jBaBgorBgEEAYI3AgEMMUwwSqAsgCoATQBp
# AGMAcgBvAHMAbwBmAHQAIABDAG8AcgBwAG8AcgBhAHQAaQBvAG6hGoAYaHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBACI7Fm/4gqnmyKQc
# aiU/4uUjL5T8Bpg0YKggEVs23ac9rh1ZiOd0S4L5OYrBZ5X8EYmtGx42iSJtStzs
# meCosFk1+S66WQRPmnAjbOqAw/DeQaqd8Nt6LwtHaEejKLd5gXlTIRmw6plBEuXK
# hrbr85vFPxIBBol2Vq8e2Psnaa0ZOItdrFdOt4iTRO6ZFV8Exhg3VBsTRj37XZYT
# 0ajNnkR9Aewtj51TPdjpB+FoIu6LqNSDaRvrO+1xhgJc4Slx9fDFo1c2UEvZtHlM
# SVbTcxTYUjBqON3z6rtpxtEeE3eDbTBOM6DDvlbbRJtzVAfdyge90SK9+59Nz430
# 4bZzEKahggH/MIIB+wYJKoZIhvcNAQkGMYIB7DCCAegCAQEwZzBTMQswCQYDVQQG
# EwJVUzEXMBUGA1UEChMOVmVyaVNpZ24sIEluYy4xKzApBgNVBAMTIlZlcmlTaWdu
# IFRpbWUgU3RhbXBpbmcgU2VydmljZXMgQ0ECEA3pK/DU2CmIGDIFCV6adogwDAYI
# KoZIhvcNAgUFAKBZMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcN
# AQkFMQ8XDTA2MDcyMTA1MTI0OVowHwYJKoZIhvcNAQkEMRIEEDCTSrNINa5P8gMF
# 90bXlwAwDQYJKoZIhvcNAQEBBQAEggEAHO4fPGDp8p8P/nRkEFAABHdRBWwqaseA
# SaUZ+PONpKRrJnCZlf9BV9lKtcliioyYWc4bc5adG2EYcntW/9LqJ2YYq7W+jBc0
# 69B2vcb7hYvwQFNgo+N9hGkvwzA3R7baHfbVXWLAvS2+SAnxIJzQUDhzIaELGyNz
# cn4yglmtUP+ZHTyMS3nGrJpENTeyp4y9l70r/nJaifmdvHMDIPiIldtQQIiIm8vu
# iy8GndloPb2mLPZUD9jdvru+F8oZAVnvJIc704T+kMpFAWXM2H1SHm4ad7HrWe45
# v1Ii5Dq1RK6dEB+Ngp7SBrjxAYfSgVBYh1M3QX/Rw15FIyLYc4lK4g==
# SIG # End signature block
